### ISSUE TITLE
can't make a new install

### ISSUE THREAD

**Issue by Sorunome** [matrix-org/matrix-appservice-discord#498]
it still expects values set for room store and user store for blank installs

**Comment by Half-Shot** [comment]
Could you expand on this? Where does it fail if the parameters are not provided?

**Comment by Half-Shot** [comment]
So with the stores...

We need to set `bridge.opts.roomStore` and `bridge.opts.userStore` to `undefined` *after* the constructor but before `run()`. But we should only do this if the store files are not found, as we may have not migrated yet. (0.5.X cannot break migrations)

**Comment by Sorunome** [comment]
it appears the actual issue was that the two values defaulted to their default ones, and for the user in question that was in a directory where the appservice didn't have write permissions, thus erroring out when it still tried to create those (empty) files

**Comment by Half-Shot** [comment]
Yes, I know :)

You can stop it from creating them by forcing undefined *after* it's set some default paths in the constructor.

**Comment by jaller94** [comment]
Fixed by https://github.com/matrix-org/matrix-appservice-discord/pull/540
