### ISSUE TITLE
Allow Blocklisting Discord users

### ISSUE THREAD

**Issue by dali99** [matrix-org/matrix-appservice-discord#577]
#576 but oppsite.

to avoid
![2019-12-12-091724_723x108_scrot](https://user-images.githubusercontent.com/990767/70694588-47ac6380-1cc0-11ea-8aa0-fcccbbedb605.png)

**Comment by auscompgeek** [comment]
Surely #550 would be better?

**Comment by jaller94** [comment]
Closing in favour of #550 because this seems to be solely about the frequency of display name changes.
