### ISSUE TITLE
Make the bridge aware that two people are the same

### ISSUE THREAD

**Issue by IngwiePhoenix** [matrix-org/matrix-appservice-discord#583]
Basically, I would like to know if it is possible to have the bridge send messages on the Matrix side as a specific user, as to map a Matrix user to a Discord user. Vice versa might be hard and require puppeting as far as I understand.

My goal is to be able to see messages I post in Discord show up with my Matrix handle in the Matrix side.

Is that possible?

**Comment by Sorunome** [comment]
The appservice already supports that via puppeting. See [the puppeting](https://github.com/Half-Shot/matrix-appservice-discord/blob/master/docs/puppeting.md) docs
