### ISSUE TITLE
adminme script is broken

### ISSUE THREAD

**Issue by zeratax** [matrix-org/matrix-appservice-discord#589]
at least on the develop branch, see: https://matrix.to/#/!OluOzqbTJgecdDIuKn:half-shot.uk/$158318120119xuTQA:dmnd.sh

**Comment by Deanosim** [comment]
Any idea on when this fix will make it to the currently public docker image? Not being able to make myself admin is a real pain.

**Comment by auscompgeek** [comment]
This has already been fixed on develop. (Perhaps this issue should be closed?)
