### ISSUE TITLE
Change API domain to discord.com

### ISSUE THREAD

**Issue by aa1874** [matrix-org/matrix-appservice-discord#611]
New guidelines sent to developers and bot owners has announced that Discord is retiring the discordapp.com URL by November.

Thus the discordapp.com references on the bot must be changed to discord.com.

**Comment by elsemieni** [comment]
It depends of Discord.js
There's an already merged pull request that changed the domain https://github.com/discordjs/discord.js/pull/4160 . However, it's still not in any release, (this pull request is from May, and the lastest version available on npm is from April) so we have to wait until a new release appears. Then, we must update the package.json to match that last version.

As you can see, for now we have to just wait :)

**Comment by Sorunome** [comment]
we still run on discord.js v11, so we'll also need to upgrade to v12 (though that would break puppeting) or use a fork that can handle user tokens.

**Comment by aa1874** [comment]
there's a guide on the discord.js guide...

**Comment by pedrofracassi** [comment]
You can pass an options object to the client to change the domain if need be: https://discord.js.org/#/docs/main/v11/typedef/ClientOptions

**Comment by okennedy** [comment]
November 7 is getting awfully close...

**Comment by Half-Shot** [comment]
There are other complications involving gateways, but the PR to fix this is #626

**Comment by auscompgeek** [comment]
This can be closed now, right?
